### ISSUE TITLE
공유 DB 연결하기 

### ISSUE THREAD

**Issue by kokojihye** [tutorLink-SYU-Capstone2023/Backend#13]
## Description 💭
멘토님이 열어주신 공유 DB 각자 프로젝트에 연결 한 후 댓글 남겨주기 

## To-do ✔️
- [x] 댓글 확인 후 모두 문제 없이 완료 되면 issue close하기

## ETC 🌷
다들 댓글 남겨주세요!

**Comment by kokojihye** [comment]
<img width="812" alt="image" src="https://github.com/tutorLink-SYU-Capstone2023/Backend/assets/95533614/eabc50b9-59bf-4bae-8efb-d5a155f222ee">

저는 연결 성공했습니다~~

**Comment by kimsquid110** [comment]
성공했습니다 👍

**Comment by Julienjang** [comment]
완료했습니다🤓
