### ISSUE TITLE
맴버 조회 Mybatis로 구현하기

### ISSUE THREAD

**Issue by kimsquid110** [tutorLink-SYU-Capstone2023/Backend#8]
## Description 💭
멤버 조회 Mybatis로 구현합니다

## To-do ✔️
- [x] 로컬 DB에 임시 데이터를 넣어 본 후, 해당 데이터가 잘 조회되는지 확인해보기

## ETC 🌷

**Comment by kokojihye** [comment]
빠르네요 👍🏻
